
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookingdb;encrypt=true;trustServerCertificate=true;
spring.datasource.username=[USERNAME]
spring.datasource.password=[PASSWORD]
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true